// security-ui/src/App.tsx
import { useEffect, useState } from 'react';

// the e2e harness points the app at its own test-env service (Playwright injects window.SECURITY_URL
// before the app boots); a human on the dev server gets the stack's default
const SECURITY = (window as unknown as { SECURITY_URL?: string }).SECURITY_URL ?? 'http://localhost:8080';

type Mode = 'signin' | 'signup' | 'inbox' | 'mfa' | 'me';
type Factor = { type: string; label: string };

const prettify = (code: string) => code.toLowerCase().replaceAll('_', ' ');

/**
 * The auth service's own face: sign in (single- or multi-factor), create an account, the "check
 * your mailbox" screen, confirming a mailed verification link, managing sign-in factors, and /me.
 * Deliberately plain — its real job is being the specs' third entry point (the cucumber-js +
 * Playwright glue drives the same features the JVM runners do). React, like the meme gallery.
 */
export function App() {
  const [mode, setMode] = useState<Mode>('signin');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [me, setMe] = useState('');
  const [token, setToken] = useState('');
  const [roles, setRoles] = useState<string[]>([]);
  const [compliant, setCompliant] = useState(true);
  const [floor, setFloor] = useState({ required: 1, have: 1 });
  const [notice, setNotice] = useState<string | null>(null);
  const [emailErrors, setEmailErrors] = useState<string[]>([]);
  const [passwordErrors, setPasswordErrors] = useState<string[]>([]);
  // multi-factor sign-in
  const [mfaTicket, setMfaTicket] = useState('');
  const [nextFactor, setNextFactor] = useState('');
  const [code, setCode] = useState('');
  // enrolment
  const [factors, setFactors] = useState<Factor[]>([]);
  const [offered, setOffered] = useState<string[]>([]);
  const [enrollingType, setEnrollingType] = useState('');
  const [enrollDisplay, setEnrollDisplay] = useState('');
  const [enrollTarget, setEnrollTarget] = useState('');
  const [enrolCode, setEnrolCode] = useState('');

  useEffect(() => {
    const mailed = new URLSearchParams(location.search).get('verify');
    if (!mailed) return;
    history.replaceState(null, '', location.pathname);
    void fetch(`${SECURITY}/verify-email`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ token: mailed }),
    }).then((r) =>
      setNotice(r.ok
        ? 'E-mail verified — sign in below.'
        : 'This verification link was already used or replaced by a newer one.'),
    );
  }, []);

  const reset = () => {
    setNotice(null);
    setEmailErrors([]);
    setPasswordErrors([]);
  };

  const switchTo = (next: Mode) => {
    setMode(next);
    reset();
  };

  const enterSession = async (accessToken: string) => {
    const meResponse = await fetch(`${SECURITY}/me`, { headers: { Authorization: `Bearer ${accessToken}` } });
    const meBody: { email: string; roles?: string[]; mfaCompliant?: boolean; requiredFactors?: number; haveFactors?: number } =
      await meResponse.json();
    setToken(accessToken);
    setMe(meBody.email);
    setRoles(meBody.roles ?? []);
    setCompliant(meBody.mfaCompliant ?? true);
    setFloor({ required: meBody.requiredFactors ?? 1, have: meBody.haveFactors ?? 1 });
    setMode('me');
    void loadFactors(accessToken);
  };

  const signIn = async () => {
    reset();
    const r = await fetch(`${SECURITY}/authenticate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    if (r.ok) {
      await enterSession((await r.json()).accessToken);
    } else if (r.status === 202) {
      // more factors owed — the first challenge is out; ask for the proof
      const body: { mfaTicket: string; nextFactor: string } = await r.json();
      setMfaTicket(body.mfaTicket);
      setNextFactor(body.nextFactor);
      setCode('');
      setMode('mfa');
    } else if (r.status === 403) {
      setNotice('E-mail not verified yet — follow the link in the mail first.');
    } else if (r.status === 429) {
      setNotice('Too many failed attempts — this source is blocked for a while.');
    } else {
      setNotice('Wrong e-mail or password.');
    }
  };

  const submitFactor = async () => {
    reset();
    const r = await fetch(`${SECURITY}/authenticate/factor`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ mfaTicket, proof: code }),
    });
    if (r.ok) {
      await enterSession((await r.json()).accessToken);
    } else if (r.status === 202) {
      setNextFactor((await r.json()).nextFactor);
      setCode('');
    } else {
      const body: { status?: string; attemptsLeft?: number } = await r.json();
      setNotice(body.status === 'WRONG_CODE'
        ? `Wrong code${body.attemptsLeft != null ? ` — ${body.attemptsLeft} tries left` : ''}.`
        : 'That sign-in expired — start over.');
      if (body.status !== 'WRONG_CODE') switchTo('signin');
    }
  };

  const signUp = async () => {
    reset();
    const r = await fetch(`${SECURITY}/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    if (r.status === 201) {
      setMode('inbox');
    } else if (r.status === 422) {
      const errors: { emailErrors?: string[]; passwordErrors?: string[] } = await r.json();
      setEmailErrors(errors.emailErrors ?? []);
      setPasswordErrors(errors.passwordErrors ?? []);
    } else {
      setNotice(`Registration failed (${r.status}).`);
    }
  };

  const factorLabel = (type: string) =>
    ({ EMAIL_CODE: 'e-mail code', SMS_CODE: 'SMS code', TOTP: 'authenticator app' } as Record<string, string>)[type] ?? type;

  const loadFactors = async (accessToken: string) => {
    const r = await fetch(`${SECURITY}/account/factors`, { headers: { Authorization: `Bearer ${accessToken}` } });
    if (r.ok) { const body = await r.json(); setFactors(body.have ?? []); setOffered(body.offered ?? []); }
  };

  const startEnrol = async (type: string) => {
    setNotice(null);
    const body = type === 'SMS_CODE' ? JSON.stringify({ target: enrollTarget }) : '{}';
    const r = await fetch(`${SECURITY}/account/factors/${type}/enroll/start`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body,
    });
    if (r.status === 202) {
      const setup: { status: string; display?: string } = await r.json();
      setEnrollingType(type);
      setEnrollDisplay(setup.display ?? '');
      setEnrolCode('');
    } else {
      setNotice('Could not start enrolment.');
    }
  };

  const confirmEnrol = async () => {
    const r = await fetch(`${SECURITY}/account/factors/${enrollingType}/enroll/confirm`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body: JSON.stringify({ code: enrolCode }),
    });
    if (r.ok) {
      setNotice(`${factorLabel(enrollingType)} enrolled — you will use it next sign-in.`);
      setEnrollingType(''); setEnrollDisplay(''); setEnrollTarget('');
      void loadFactors(token);
    } else {
      setNotice('Wrong code — enrolment not completed.');
    }
  };

  const signOut = () => {
    setToken('');
    setMe('');
    setRoles([]);
    setFactors([]);
    switchTo('signin');
  };

  return (
    <div className="card">
      {mode === 'me' && (
        <>
          <h3>Signed in</h3>
          <p>You are <b data-testid="signed-in-email">{me}</b> ({roles.join(', ')}).</p>

          {!compliant && (
            <p data-testid="mfa-required" className="notice">
              Your role needs {floor.required} sign-in factors — you have {floor.have}. Add another
              below to unlock everything.
            </p>
          )}

          <h4>Sign-in factors</h4>
          <ul data-testid="factor-list">
            {factors.map((f) => <li key={f.type}>{f.label}</li>)}
            {factors.length === 0 && <li><i>password only</i></li>}
          </ul>
          {!enrollingType && offered.filter((t) => !factors.some((f) => f.type === t)).map((type) => (
            <div key={type}>
              {type === 'SMS_CODE' && (
                <input data-testid="enroll-phone" placeholder="+48…"
                       value={enrollTarget} onChange={(e) => setEnrollTarget(e.target.value)} />
              )}
              <button data-testid={`add-${type}`} onClick={() => void startEnrol(type)}>
                Add {factorLabel(type)}
              </button>
            </div>
          ))}
          {enrollingType && (
            <div>
              {enrollDisplay && (
                <p data-testid="enroll-otpauth" style={{ wordBreak: 'break-all', fontSize: '0.8rem' }}>
                  Scan this in your authenticator app: <code>{enrollDisplay}</code>
                </p>
              )}
              <input data-testid="enroll-code"
                     placeholder={enrollDisplay ? 'code from your app' : 'code we sent you'}
                     value={enrolCode} onChange={(e) => setEnrolCode(e.target.value)} />
              <button data-testid="enroll-submit" onClick={() => void confirmEnrol()}>Confirm</button>
            </div>
          )}
          <p><button data-testid="sign-out" onClick={signOut}>Sign out</button></p>
        </>
      )}

      {mode === 'mfa' && (
        <>
          <h3 data-testid="mfa-screen">One more step</h3>
          <p>We sent a {prettify(nextFactor)} to your e-mail — enter it to finish signing in.</p>
          <form onSubmit={(e) => { e.preventDefault(); void submitFactor(); }}>
            <input data-testid="mfa-code" placeholder="sign-in code" value={code}
                   onChange={(e) => setCode(e.target.value)} autoFocus />
            <button data-testid="mfa-submit" type="submit">Sign in</button>
          </form>
        </>
      )}

      {mode === 'inbox' && (
        <>
          <h3 data-testid="inbox-screen">Check your mailbox</h3>
          <p>We sent a mail to <b>{email}</b> — follow it to continue.</p>
          <button data-testid="back-to-signin" onClick={() => switchTo('signin')}>Back to sign in</button>
        </>
      )}

      {(mode === 'signin' || mode === 'signup') && (
        <>
          <nav>
            <button data-testid="tab-signin" className={mode === 'signin' ? 'active' : ''}
                    onClick={() => switchTo('signin')}>Sign in</button>
            <button data-testid="tab-signup" className={mode === 'signup' ? 'active' : ''}
                    onClick={() => switchTo('signup')}>Create account</button>
          </nav>
          <form onSubmit={(e) => { e.preventDefault(); void (mode === 'signup' ? signUp() : signIn()); }}>
            <input data-testid="email" type="text" placeholder="e-mail" autoComplete="email"
                   value={email} onChange={(e) => setEmail(e.target.value)} />
            <input data-testid="password" type="password" placeholder="password"
                   autoComplete={mode === 'signup' ? 'new-password' : 'current-password'}
                   value={password} onChange={(e) => setPassword(e.target.value)} />
            <button data-testid="submit" type="submit">{mode === 'signup' ? 'Create account' : 'Sign in'}</button>
          </form>
        </>
      )}

      {notice && <p data-testid="notice" className="notice">{notice}</p>}
      {(emailErrors.length > 0 || passwordErrors.length > 0) && (
        <div data-testid="validation-errors" className="notice">
          That will not do:
          <ul data-testid="email-errors">{emailErrors.map((e) => <li key={e}>{prettify(e)}</li>)}</ul>
          <ul data-testid="password-errors">{passwordErrors.map((e) => <li key={e}>{prettify(e)}</li>)}</ul>
        </div>
      )}
    </div>
  );
}

// security-ui/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';

// the e2e harness points the app at its own test-env service instance (Playwright injects
// window.SECURITY_URL before the app boots); a human on the dev server gets the stack's default
const SECURITY = (window as unknown as { SECURITY_URL?: string }).SECURITY_URL ?? 'http://localhost:8080';

type Mode = 'signin' | 'signup' | 'inbox' | 'me';

/**
 * The auth service's own face: sign in, create an account, land on the "check your mailbox"
 * screen, confirm a mailed verification link (?verify=<token>), and see who you are (/me).
 * Deliberately plain — its real job is being the specs' third entry point: the cucumber-js +
 * Playwright glue in e2e/ drives the very same register.feature and authenticate.feature the
 * JVM runners do, through the data-testid hooks below.
 */
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="card">
      <ng-container *ngIf="mode === 'me'">
        <h3>Signed in</h3>
        <p>You are <b data-testid="signed-in-email">{{ me }}</b> ({{ roles.join(', ') }}).</p>
        <button data-testid="sign-out" (click)="signOut()">Sign out</button>
      </ng-container>

      <ng-container *ngIf="mode === 'inbox'">
        <h3 data-testid="inbox-screen">Check your mailbox</h3>
        <p>We sent a mail to <b>{{ email }}</b> — follow it to continue.</p>
        <button data-testid="back-to-signin" (click)="switchTo('signin')">Back to sign in</button>
      </ng-container>

      <ng-container *ngIf="mode === 'signin' || mode === 'signup'">
        <nav>
          <button data-testid="tab-signin" [class.active]="mode === 'signin'" (click)="switchTo('signin')">Sign in</button>
          <button data-testid="tab-signup" [class.active]="mode === 'signup'" (click)="switchTo('signup')">Create account</button>
        </nav>
        <form (ngSubmit)="mode === 'signup' ? signUp() : signIn()">
          <input data-testid="email" name="email" type="text" placeholder="e-mail" [(ngModel)]="email">
          <input data-testid="password" name="password" type="password" placeholder="password" [(ngModel)]="password">
          <button data-testid="submit" type="submit">{{ mode === 'signup' ? 'Create account' : 'Sign in' }}</button>
        </form>
      </ng-container>

      <p *ngIf="notice" data-testid="notice" class="notice">{{ notice }}</p>
      <div *ngIf="emailErrors.length || passwordErrors.length" data-testid="validation-errors" class="notice">
        That will not do:
        <ul data-testid="email-errors"><li *ngFor="let e of emailErrors">{{ prettify(e) }}</li></ul>
        <ul data-testid="password-errors"><li *ngFor="let e of passwordErrors">{{ prettify(e) }}</li></ul>
      </div>
    </div>
  `,
  styles: [`
    .card { background: #fff; border: 1px solid #e3e5e8; border-radius: 10px; padding: 28px; width: 22rem; }
    nav { display: flex; gap: .5rem; margin-bottom: 1rem; }
    nav button { background: none; border: none; padding: .3rem .1rem; cursor: pointer; color: #6a737d; }
    nav button.active { color: #1a7fff; border-bottom: 2px solid #1a7fff; }
    form { display: grid; gap: .6rem; }
    input { padding: .5rem; border: 1px solid #ccc; border-radius: 6px; }
    form > button, .card > button { padding: .5rem; border-radius: 6px; border: 1px solid #1a7fff; background: #1a7fff; color: #fff; cursor: pointer; }
    .notice { color: #9a3412; background: #fff7ed; border-radius: 6px; padding: .5rem .7rem; }
    ul { margin: .3rem 0 0; padding-left: 1.2rem; }
  `],
})
export class AppComponent implements OnInit {
  mode: Mode = 'signin';
  email = '';
  password = '';
  me = '';
  roles: string[] = [];
  notice: string | null = null;
  emailErrors: string[] = [];
  passwordErrors: string[] = [];

  // fetch resolutions land outside Angular's zone here, so change detection is nudged
  // explicitly after every async update — the view is small and this keeps it bulletproof
  constructor(private readonly cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    // the verification mail links here (?verify=<token>); confirm it on arrival
    const mailed = new URLSearchParams(location.search).get('verify');
    if (!mailed) return;
    history.replaceState(null, '', location.pathname);
    void fetch(`${SECURITY}/verify-email`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ token: mailed }),
    }).then((r) => {
      this.notice = r.ok
        ? 'E-mail verified — sign in below.'
        : 'This verification link was already used or replaced by a newer one.';
      this.cdr.detectChanges();
    });
  }

  async signIn(): Promise<void> {
    this.reset();
    const r = await fetch(`${SECURITY}/authenticate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: this.email, password: this.password }),
    });
    if (r.ok) {
      const body: { accessToken: string } = await r.json();
      const meResponse = await fetch(`${SECURITY}/me`, {
        headers: { Authorization: `Bearer ${body.accessToken}` },
      });
      const meBody: { email: string; roles?: string[] } = await meResponse.json();
      this.me = meBody.email;
      this.roles = meBody.roles ?? [];
      this.mode = 'me';
    } else if (r.status === 403) {
      this.notice = 'E-mail not verified yet — follow the link in the mail first.';
    } else if (r.status === 429) {
      this.notice = 'Too many failed attempts — this source is blocked for a while.';
    } else {
      this.notice = 'Wrong e-mail or password.';
    }
    this.cdr.detectChanges();
  }

  async signUp(): Promise<void> {
    this.reset();
    const r = await fetch(`${SECURITY}/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: this.email, password: this.password }),
    });
    if (r.status === 201) {
      // taken addresses answer identically (anti-enumeration) — the mail says which it was
      this.mode = 'inbox';
    } else if (r.status === 422) {
      const errors: { emailErrors?: string[]; passwordErrors?: string[] } = await r.json();
      this.emailErrors = errors.emailErrors ?? [];
      this.passwordErrors = errors.passwordErrors ?? [];
    } else {
      this.notice = `Registration failed (${r.status}).`;
    }
    this.cdr.detectChanges();
  }

  signOut(): void {
    this.me = '';
    this.roles = [];
    this.switchTo('signin');
  }

  switchTo(mode: Mode): void {
    this.mode = mode;
    this.reset();
  }

  prettify(code: string): string {
    return code.toLowerCase().replaceAll('_', ' ');
  }

  private reset(): void {
    this.notice = null;
    this.emailErrors = [];
    this.passwordErrors = [];
  }
}
